// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdLnwTPZ2xqLgb-hdmBzMOMjwoLA153I',
    appId: '1:776954477401:android:dd95789da5c01b5bab6a48',
    messagingSenderId: '776954477401',
    projectId: 'speed-guardian-47dfe',
    storageBucket: 'speed-guardian-47dfe.firebasestorage.app',
    androidClientId: "776954477401-srdsqu03is5b4j050j7vulvlktsf6sjk.apps.googleusercontent.com"
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY3b6X_MnyrRz2pxj1fygpf7lqLBuyj2o',
    appId: '1:776954477401:ios:e5a6330243115e68ab6a48',
    messagingSenderId: '776954477401',
    projectId: 'speed-guardian-47dfe',
    storageBucket: 'speed-guardian-47dfe.firebasestorage.app',
    iosBundleId: 'com.app.speedguardian',
  );
}
